services:
  mysql:
    container_name: cf_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: hathienlon
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - coffee-shop
    restart: unless-stopped

  phpmyadmin:
    container_name: cf_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: cf_mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
    ports:
      - 8100:80
    networks:
      - coffee-shop
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: cf_redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
        - coffee-shop
    restart: unless-stopped
  
  elasticsearch:
    image: elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - node.name=es_coffee_shop
      - cluster.name=coffee_shop
      - discovery.type=single-node
      - xpack.security.enabled=false  # Tắt xác thực
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"
    volumes:  
      - esdata:/usr/share/elasticsearch/data
    networks:
      - coffee-shop

  kibana:
    image: kibana:8.15.2
    container_name: kibana
    environment:
      - node.name=kib_coffee_shop
      - cluster.name=coffee_shop
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Địa chỉ của Elasticsearch 
    ports:
      - "5601:5601"  
    depends_on:
      - elasticsearch
    networks:
      - coffee-shop


networks:
  coffee-shop:
    driver: bridge

volumes:
  mysql:
  phpmyadmin:
  redis:
  esdata:
    driver: local