server:
  port: 8081
  servlet:
    context-path: /coffee
spring:
  application:
    name: coffee-shop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coffee_shop
    username: root
    password: hathienlon
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379
    elasticsearch:
      cluster-name: es_coffee_shop
      rest:
        uris: http://localhost:9200

http:
  client:
    recommend: 'http://localhost:5000/recommendations'

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

payment: ##Configuration for development environment
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnUrl: http://localhost:8081/coffee/api/v1/payment/vn-pay-callback
    tmnCode: "G34AWAZ1"
    secretKey: "6EEJXN2NWFRHE3QKBLNLZNPOWST5I0FD"
    version: "2.1.0"
    command: "pay"
    orderType: "other"

  momo:
    accessKey: 'F8BBA842ECF85'
    secretKey: 'K951B6PE1waDMi640xX08PD3vg6EkVlz'
    orderInfo: 'pay with MoMo'
    partnerCode: 'MOMO'
    redirectUrl: 'http://localhost:8081/coffee/api/v1/payment/vn-pay-callback'
    ipnUrl: ''
    requestType: 'payWithMethod'
    extraData: ''
    orderGroupId: ''
    autoCapture: true
    lang: 'vi'


